version : "2.4"

services:
# database service: named as mongodb
  mongodb:
    image: mongo
    container_name: mongodb_cont
    restart: always  
    networks:
      - mern_2
    volumes:
      # - ./trainee_backend/database/storage/:/data/db    # bind mount
      - storage:/data/db                                # volume mount

# backend service: named as trainee_backend
  trainee_backend:
    build:
      dockerfile: Dockerfile
      context: ./trainee_backend/
    container_name: trainee_backend_cont
    restart: always
    networks:
      - mern_2
      - mern_1
    mem_limit: 300m
    cpus: '0.1'
    depends_on:
      - mongodb
    
# frontend service: named as trainee_frontend
  trainee_frontend:
    build:
      dockerfile: Dockerfile
      context: ./trainee_frontend/
    container_name: trainee_frontend_cont
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - mern_1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/:/etc/nginx/ssl
    depends_on:
      - trainee_backend

# networks used for connecting different containers
networks:
  mern_1:
    driver: bridge
  mern_2:
# volumes used 
volumes:                   # volume mount declared
  storage:          

